articles/urls.py
from django.urls import path
from . import views

app_name = 'articles' 

urlpatterns = [
    path('', views.index, name= 'index'),
    path('create/', views.create, name = 'create'),
]

modeform2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

articles/models.py
from django.db import models


# Create your models here.

class Article(models.Model) : 
    title = models.CharField(max_length = 50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.

def index(request) : 
    articles = Article.objects.all()

    context = {
        'articles' : articles
    }

    return render(request, 'index.html', context) 

def create(request) : 
    if request.method == 'POST':
        form = ArticleForm(request,POST)

        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', id=article.id)
        
    else:
        form = ArticleForm()

    context = {
            'form' : form,
    }

    return render(request, 'create.html', context)

articles/templates/create.html
{% extends 'base.html'%}

{% block body %}

    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>

{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <h1>index</h1>

    {% for article in articles %}
        <p>{{article.title}}</p>
        <a href="{% url 'articles:detail' id=article.id %}">detail</a>

        <hr>
    {% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'articles:index' %}">Home</a>
    
    
    {% block body %}

    {% endblock %}
</body>
</html>